export const MIXPANEL_APP_TOKEN = process.env.REACT_APP_MIXPANEL_TOKEN
export const MIXPANEL_PROXY_DOMAIN = process.env.REACT_APP_MIXPANEL_PROXY_DOMAIN
export const MIXPANEL_DEBUG_MODE = process.env.REACT_APP_MIXPANEL_DEBUG_MODE